// final_project/frontend-vue/src/components/news/NewsList.vue
<script setup lang="ts">
import type { NewsItem } from "../../lib/news";
import NewsCard from "./NewsCard.vue";

defineProps<{ items: NewsItem[] }>();
</script>

<template>
  <div class="divide-y divide-border">
    <NewsCard v-for="item in items" :key="item.id" :item="item" />
  </div>
</template>

// final_project/frontend/components/news/NewsList.tsx
import type { NewsItem } from "@/lib/news";
import { NewsCard } from "./NewsCard";

export function NewsList({ items }: { items: NewsItem[] }) {
  return (
    <div className="divide-y divide-border">
      {items.map((item) => (
        <NewsCard key={item.id} item={item} />
      ))}
    </div>
  );
}
