// final_project/frontend/components/about/GreetingForm.tsx
"use client";

import { useState, type FormEvent } from "react";
import { useLang } from "@/lib/i18n";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

export function GreetingForm() {
  const { t, tf } = useLang();
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [name, setName] = useState<string | null>(null);

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    const full = `${firstName} ${lastName}`.trim();
    setName(full.length > 0 ? full : null);
  };

  return (
    <form onSubmit={onSubmit} className="space-y-5" noValidate>
      <div className="grid gap-4 sm:grid-cols-2">
        <label className="block">
          <span className="mb-1.5 block text-sm font-medium text-foreground">
            {t("about.firstNameLabel")}
          </span>
          <Input
            value={firstName}
            onChange={(e) => setFirstName(e.target.value)}
            placeholder={t("about.firstNamePlaceholder")}
            autoComplete="given-name"
            name="firstName"
          />
        </label>
        <label className="block">
          <span className="mb-1.5 block text-sm font-medium text-foreground">
            {t("about.lastNameLabel")}
          </span>
          <Input
            value={lastName}
            onChange={(e) => setLastName(e.target.value)}
            placeholder={t("about.lastNamePlaceholder")}
            autoComplete="family-name"
            name="lastName"
          />
        </label>
      </div>
      <Button type="submit">{t("about.greetButton")}</Button>
      {name !== null ? (
        <p className="text-lg font-semibold tracking-tight text-accent-hover">
          {tf("about.welcome", { name })}
        </p>
      ) : null}
    </form>
  );
}

// final_project/frontend-vue/src/components/about/GreetingForm.vue
<script setup lang="ts">
import { ref } from "vue";
import { useI18n } from "../../i18n";
import Button from "../ui/Button.vue";
import Input from "../ui/Input.vue";

const { t, tf } = useI18n();
const firstName = ref("");
const lastName = ref("");
const name = ref<string | null>(null);

function onSubmit(): void {
  const full = `${firstName.value} ${lastName.value}`.trim();
  name.value = full.length > 0 ? full : null;
}
</script>

<template>
  <form class="space-y-5" noValidate @submit.prevent="onSubmit">
    <div class="grid gap-4 sm:grid-cols-2">
      <label class="block">
        <span class="mb-1.5 block text-sm font-medium text-foreground">
          {{ t("about.firstNameLabel") }}
        </span>
        <Input
          v-model="firstName"
          :placeholder="t('about.firstNamePlaceholder')"
          auto-complete="given-name"
          name="firstName"
        />
      </label>
      <label class="block">
        <span class="mb-1.5 block text-sm font-medium text-foreground">
          {{ t("about.lastNameLabel") }}
        </span>
        <Input
          v-model="lastName"
          :placeholder="t('about.lastNamePlaceholder')"
          auto-complete="family-name"
          name="lastName"
        />
      </label>
    </div>
    <Button type="submit">{{ t("about.greetButton") }}</Button>
    <p v-if="name !== null" class="text-lg font-semibold tracking-tight text-accent-hover">
      {{ tf("about.welcome", { name }) }}
    </p>
  </form>
</template>
